# Generated by Django 5.1 on 2024-08-22 13:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(choices=[('ICICI Life', 'ICICI Life'), ('Max Life', 'Max Life'), ('HDFC Life', 'HDFC Life')], max_length=50)),
                ('application_number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]*$')])),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}$')])),
                ('date_of_birth', models.DateField()),
                ('policy_cover', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2500000), django.core.validators.MaxValueValidator(50000000)])),
                ('policy_status', models.CharField(choices=[('Requirements Awaited', 'Requirements Awaited'), ('Requirements Closed', 'Requirements Closed'), ('Underwriting', 'Underwriting'), ('Policy Issued', 'Policy Issued'), ('Policy Rejected', 'Policy Rejected')], max_length=50)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_type', models.CharField(blank=True, choices=[('Tele Medicals', 'Tele Medicals'), ('Physical Medicals', 'Physical Medicals')], max_length=50, null=True)),
                ('medical_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Waiting for Report', 'Waiting for Report'), ('Done', 'Done')], max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='policies.policy')),
            ],
        ),
    ]
