# Generated by Django 5.1 on 2024-08-23 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Policy', 'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterField(
            model_name='policy',
            name='application_number',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
